### ISSUE TITLE
Links are broken in CONTRIBUTING.md

### ISSUE THREAD

**Issue by nishit-prasad** [stuartelimu/vaccination-centres#16]
Few links are broken in CONTRIBUTING.md
Reason being that some are just placeholders and some just don't work.
I can work on fixing this issue. Feel free to assign to me

**Comment by stuartelimu** [comment]
Yes, that's right. 
You could as well look at issue #17 and come up with something.

**Comment by nishit-prasad** [comment]
@stuartelimu The PR is ready!
