### ISSUE TITLE
Create a CONTRIBUTING.md file

### ISSUE THREAD

**Issue by stuartelimu** [stuartelimu/vaccination-centres#7]
Create a CONTRIBUTING.md file with development instructions

**Comment by nishit-prasad** [comment]
Hello! I am new to open source and would like to work on this. Can I take this up?

I can contribute more on other issues but probably would need some doc link on any instructions to set up the environment.

**Comment by stuartelimu** [comment]
That would be awesome Prasad, unfortunately this particular issue has been worked on but there's room for improvement.
The set up instructions are in this file itself. I am more than willing to help you with your first contribution.
Do reach out if you get stuck, I'll set up a call, cheers :+1:

**Comment by nishit-prasad** [comment]
Sounds good @stuartelimu thank you!

Can you assign this issue to me?

**Comment by nishit-prasad** [comment]
@stuartelimu Here's the [PR](https://github.com/stuartelimu/vaccination-centres/pull/15). Hope you like it!

I have added great details in it (that includes stuff I ran into when I tried to set up)

I would love to contribute more. 😄

**Comment by stuartelimu** [comment]
Thanks so much, You did good :+1: 
The sky is the limit, feel free to make more contributions, open issues and PRs.
